package game

import (
	"strings"
	"testing"
)

func TestTMoveDown(t *testing.T) {
	tetro := NewTTetro()
	t.Logf("curr:\n%s\n", toString(tetro))

	tetro.MoveVert(1)
	expected := strings.TrimSpace(`
..........
...###....
....#.....
..........
`)

	eq(t, expected, toString(tetro))
}

func TestTMoveRight(t *testing.T) {
	tetro := NewTTetro()
	t.Logf("curr:\n%s\n", toString(tetro))

	tetro.MoveHoriz(1)
	expected := strings.TrimSpace(`
....###...
.....#....
..........
..........
`)

	eq(t, expected, toString(tetro))
}

func TestTMoveLeft(t *testing.T) {
	tetro := NewTTetro()
	t.Logf("curr:\n%s\n", toString(tetro))

	tetro.MoveHoriz(-1)
	expected := strings.TrimSpace(`
..###.....
...#......
..........
..........
`)

	eq(t, expected, toString(tetro))
}

func TestTRotate(t *testing.T) {
	tetro := NewTTetro()
	tetro.MoveVert(1)
	expected := []string{
		strings.TrimSpace(`
....#.....
....##....
....#.....
..........
`),
		strings.TrimSpace(`
....#.....
...###....
..........
..........
`),
		strings.TrimSpace(`
....#.....
...##.....
....#.....
..........
`),
		strings.TrimSpace(`
..........
...###....
....#.....
..........
`),
	}

	for _, exp := range expected {
		t.Logf("\ncurr: %v\n", tetro.Points)
		tetro.Rotate()
		eq(t, exp, toString(tetro))
	}
}

func TestIMoveDown(t *testing.T) {
	tetro := NewITetro()
	t.Logf("curr:\n%s\n", toString(tetro))

	tetro.MoveVert(1)
	expected := strings.TrimSpace(`
..........
...####...
..........
..........
`)
	eq(t, expected, toString(tetro))
}

func TestIMoveRight(t *testing.T) {
	tetro := NewITetro()
	t.Logf("curr:\n%s\n", toString(tetro))

	tetro.MoveHoriz(1)
	expected := strings.TrimSpace(`
....####..
..........
..........
..........
`)
	eq(t, expected, toString(tetro))
}

func TestIMoveLeft(t *testing.T) {
	tetro := NewITetro()
	t.Logf("curr:\n%s\n", toString(tetro))

	tetro.MoveHoriz(-1)
	expected := strings.TrimSpace(`
..####....
..........
..........
..........
`)
	eq(t, expected, toString(tetro))
}

func TestIRotate(t *testing.T) {
	tetro := NewITetro()
	tetro.MoveVert(1)

	expected := []string{
		strings.TrimSpace(`
.....#....
.....#....
.....#....
.....#....
`),
		strings.TrimSpace(`
..........
...####...
..........
..........
`),
	}

	for _, exp := range expected {
		t.Logf("\ncurr: %v\n", tetro.Points)
		tetro.Rotate()
		eq(t, exp, toString(tetro))
	}
}

func TestOMoveDown(t *testing.T) {
	tetro := NewOTetro()
	t.Logf("curr:\n%s\n", toString(tetro))

	tetro.MoveVert(1)
	expected := strings.TrimSpace(`
..........
....##....
....##....
..........
`)
	eq(t, expected, toString(tetro))
}

func TestOMoveRight(t *testing.T) {
	tetro := NewOTetro()
	t.Logf("curr:\n%s\n", toString(tetro))

	tetro.MoveHoriz(1)
	expected := strings.TrimSpace(`
.....##...
.....##...
..........
..........
`)
	eq(t, expected, toString(tetro))
}

func TestOMoveLeft(t *testing.T) {
	tetro := NewOTetro()
	t.Logf("curr:\n%s\n", toString(tetro))

	tetro.MoveHoriz(-1)
	expected := strings.TrimSpace(`
...##.....
...##.....
..........
..........
`)
	eq(t, expected, toString(tetro))
}

func TestORotate(t *testing.T) {
	tetro := NewOTetro()
	tetro.MoveVert(1)

	expected := strings.TrimSpace(`
..........
....##....
....##....
..........
`)

	t.Logf("\ncurr: %v\n", tetro.Points)
	tetro.Rotate()
	eq(t, expected, toString(tetro))
	tetro.Rotate()
	eq(t, expected, toString(tetro))
}

func TestSMoveDown(t *testing.T) {
	tetro := NewSTetro()
	t.Logf("curr:\n%s\n", toString(tetro))

	tetro.MoveVert(1)
	expected := strings.TrimSpace(`
..........
....##....
...##.....
..........
`)
	eq(t, expected, toString(tetro))
}

func TestSMoveRight(t *testing.T) {
	tetro := NewSTetro()
	t.Logf("curr:\n%s\n", toString(tetro))

	tetro.MoveHoriz(1)
	expected := strings.TrimSpace(`
.....##...
....##....
..........
..........
`)
	eq(t, expected, toString(tetro))
}

func TestSMoveLeft(t *testing.T) {
	tetro := NewSTetro()
	t.Logf("curr:\n%s\n", toString(tetro))

	tetro.MoveHoriz(-1)
	expected := strings.TrimSpace(`
...##.....
..##......
..........
..........
`)
	eq(t, expected, toString(tetro))
}

func TestSRotate(t *testing.T) {
	tetro := NewSTetro()
	tetro.MoveVert(1)

	expected := []string{
		strings.TrimSpace(`
....#.....
....##....
.....#....
..........
`),
		strings.TrimSpace(`
..........
....##....
...##.....
..........
`),
	}

	for _, exp := range expected {
		t.Logf("\ncurr: %v\n", tetro.Points)
		tetro.Rotate()
		eq(t, exp, toString(tetro))
	}
}

func TestZMoveDown(t *testing.T) {
	tetro := NewZTetro()
	t.Logf("curr:\n%s\n", toString(tetro))

	tetro.MoveVert(1)
	expected := strings.TrimSpace(`
..........
...##.....
....##....
..........
`)
	eq(t, expected, toString(tetro))
}

func TestZMoveRight(t *testing.T) {
	tetro := NewZTetro()
	t.Logf("curr:\n%s\n", toString(tetro))

	tetro.MoveHoriz(1)
	expected := strings.TrimSpace(`
....##....
.....##...
..........
..........
`)
	eq(t, expected, toString(tetro))
}

func TestZMoveLeft(t *testing.T) {
	tetro := NewZTetro()
	t.Logf("curr:\n%s\n", toString(tetro))

	tetro.MoveHoriz(-1)
	expected := strings.TrimSpace(`
..##......
...##.....
..........
..........
`)
	eq(t, expected, toString(tetro))
}

func TestZRotate(t *testing.T) {
	tetro := NewZTetro()
	tetro.MoveVert(1)

	expected := []string{
		strings.TrimSpace(`
.....#....
....##....
....#.....
..........
`),
		strings.TrimSpace(`
..........
...##.....
....##....
..........
`),
	}

	for _, exp := range expected {
		t.Logf("\ncurr: %v\n", tetro.Points)
		tetro.Rotate()
		eq(t, exp, toString(tetro))
	}
}

func TestLMoveDown(t *testing.T) {
	tetro := NewLTetro()
	t.Logf("curr:\n%s\n", toString(tetro))

	tetro.MoveVert(1)
	expected := strings.TrimSpace(`
..........
...###....
...#......
..........
`)
	eq(t, expected, toString(tetro))
}

func TestLMoveRight(t *testing.T) {
	tetro := NewLTetro()
	t.Logf("curr:\n%s\n", toString(tetro))

	tetro.MoveHoriz(1)
	expected := strings.TrimSpace(`
....###...
....#.....
..........
..........
`)
	eq(t, expected, toString(tetro))
}

func TestLMoveLeft(t *testing.T) {
	tetro := NewLTetro()
	t.Logf("curr:\n%s\n", toString(tetro))

	tetro.MoveHoriz(-1)
	expected := strings.TrimSpace(`
..###.....
..#.......
..........
..........
`)
	eq(t, expected, toString(tetro))
}

func TestLRotate(t *testing.T) {
	tetro := NewLTetro()
	tetro.MoveVert(1)

	expected := []string{
		strings.TrimSpace(`
....#.....
....#.....
....##....
..........
`),
		strings.TrimSpace(`
.....#....
...###....
..........
..........
`),
		strings.TrimSpace(`
...##.....
....#.....
....#.....
..........
`),
		strings.TrimSpace(`
..........
...###....
...#......
..........
`),
	}

	for _, exp := range expected {
		t.Logf("\ncurr: %v\n", tetro.Points)
		tetro.Rotate()
		eq(t, exp, toString(tetro))
	}
}

func TestJMoveDown(t *testing.T) {
	tetro := NewJTetro()
	t.Logf("curr:\n%s\n", toString(tetro))

	tetro.MoveVert(1)
	expected := strings.TrimSpace(`
..........
...###....
.....#....
..........
`)
	eq(t, expected, toString(tetro))
}

func TestJMoveRight(t *testing.T) {
	tetro := NewJTetro()
	t.Logf("curr:\n%s\n", toString(tetro))

	tetro.MoveHoriz(1)
	expected := strings.TrimSpace(`
....###...
......#...
..........
..........
`)
	eq(t, expected, toString(tetro))
}

func TestJMoveLeft(t *testing.T) {
	tetro := NewJTetro()
	t.Logf("curr:\n%s\n", toString(tetro))

	tetro.MoveHoriz(-1)
	expected := strings.TrimSpace(`
..###.....
....#.....
..........
..........
`)
	eq(t, expected, toString(tetro))
}

func TestJRotate(t *testing.T) {
	tetro := NewJTetro()
	tetro.MoveVert(1)

	expected := []string{
		strings.TrimSpace(`
....##....
....#.....
....#.....
..........
`),
		strings.TrimSpace(`
...#......
...###....
..........
..........
`),
		strings.TrimSpace(`
....#.....
....#.....
...##.....
..........
`),
		strings.TrimSpace(`
..........
...###....
.....#....
..........
`),
	}

	for _, exp := range expected {
		t.Logf("\ncurr: %v\n", tetro.Points)
		tetro.Rotate()
		eq(t, exp, toString(tetro))
	}
}

func eq[T comparable](t *testing.T, expected, actual T) {
	if expected != actual {
		t.Fatalf("\n--- expected:\n%v\n--- got:\n%v", expected, actual)
	}
}

func toString(tetro *Tetromino) string {
	field := []byte(strings.TrimSpace(`
..........
..........
..........
..........
`))

	for _, p := range tetro.Points {
		i := 11*p.Y + p.X // 11 is field width + \n
		field[i] = '#'
	}

	return string(field)
}
